//
//  StorjErrorCodes.h
//  SwiftyStorj
//
//  Created by Barterio on 1/30/18.
//  Copyright © 2018 angu2111. All rights reserved.
//
@import Foundation;

FOUNDATION_EXPORT NSString * const STORJ_E_VERIFY_KEYS;
FOUNDATION_EXPORT NSString * const STORJ_E_IMPORT_KEYS;
FOUNDATION_EXPORT NSString * const STORJ_E_KEYS_EXISTS;
FOUNDATION_EXPORT NSString * const STORJ_E_GET_KEYS;
FOUNDATION_EXPORT NSString * const STORJ_E_REGISTER;
FOUNDATION_EXPORT NSString * const STORJ_E_GENERATE_MNEMONIC;
FOUNDATION_EXPORT NSString * const STORJ_E_CHECK_MNEMONIC;
FOUNDATION_EXPORT NSString * const STORJ_E_KEYS_NOT_FOUND;
FOUNDATION_EXPORT NSString * const STORJ_E_GET_BUCKETS;
FOUNDATION_EXPORT NSString * const STORJ_E_CREATE_BUCKET;
